add_newline = false
format = """
$directory\
$git_branch\
$git_status\
$character\
"""
right_format = "$all"

# A continuation prompt that displays two filled-in arrows
# continuation_prompt = '▶▶ '

[directory]
    truncate_to_repo = false
    truncation_symbol = ".../"

[git_branch]
    format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
    format = "([$all_status$ahead_behind]($style) )"
    style = "green bold"
    ahead = "⇡${count}"
    diverged = "⇕⇡${ahead_count}⇣${behind_count}"
    behind = "⇣${count}"
    untracked = "?${count}"
    modified = "!${count}"
    staged = "+${count}"

[python]
    format = '[${symbol}(${version} )(\($virtualenv\) )]($style)'

[package]
    disabled = true

[cmd_duration]
    disabled = true

[aws]
    format = "[$symbol$profile]($style) "
    style = "yellow"
    symbol = " "

[kubernetes]
    symbol = "☸ "
    style = "blue bold"
    detect_env_vars = ['KUBE_CONTEXT_ACTIVE']
    # format = '[$symbol$context( \($namespace\))]($style) '
    format = "[$symbol($namespace)]($style) "
    disabled = false

[[kubernetes.contexts]]
    # aws eks context
    context_pattern = 'arn.*\/(?P<cluster>[\w\/-]+)'
    context_alias = "aws:$cluster"
